### ISSUE TITLE
Work on README.md

### ISSUE THREAD

**Issue by SarthakSKumar** [SarthakSKumar/Chatroom-App#12]
Come up with a innovative README.md which showcases the project, and includes steps to enable users deploy it in their local systems

**Comment by Rajdeep1311** [comment]
@SarthakSKumar Sir, Can I work on the documentation of this project ? I'm a very first timer and hoping to start my journey in the field of open source with the help of your project.

**Comment by SarthakSKumar** [comment]
Hello @Rajdeep1311. Sure you can work on the issue. Make sure to enhance the README by using badges, images, banners, anything you would like to add. It should consist of some info on the chatroom app, the tech stack used, cloning and deploying the project locally etc. You can have a look at this README for reference:

https://github.com/prathimacode-hub/IoT-Spot

Please let me know how much time would you require to resolve this issue. Thanks!

**Comment by Rajdeep1311** [comment]
Can you please tell me the steps about cloning and deploying the project locally ? I have alreadt started to gather images and stuff for the README and I think I would require a week to work on this as I am a complete fresher in this field , I would require some time. Also, can I please get the logo of the chatroom App "MentomatchChat".

**Comment by SarthakSKumar** [comment]
You wouldn't need to deploy the project locally if you are just working on the README.md file. Just clone the fork of the repo to your local system, make the changes to the README.md file and push it to the fork. Create a PR mentioning the issue number and I will review your PR. 
I will update you regarding the logo and deployment steps here, in a while

**Comment by Rajdeep1311** [comment]
Sure sir.

**Comment by SarthakSKumar** [comment]
There is no logo for the project as of now. Just a banner with the title will do. 
https://github.com/SarthakSKumar/Notes-Web-App
https://github.com/SarthakSKumar/Hacknight4.0-Leaderboard

You can refer to these links, for deployment steps. Available scripts in this project are 'npm start' and 'npm run dev'.

**Comment by Rajdeep1311** [comment]
Okay

**Comment by Rajdeep1311** [comment]
Please check if you have got my PR

**Comment by SarthakSKumar** [comment]
Please mention the issue number that you are solving, in the PR

**Comment by Rajdeep1311** [comment]
Issue number mentioned please review the changes of my PR
